---
name: python-perf

on:
  pull_request:
    types: [labeled]
    paths:
      - '**'

jobs:
  perfs:
    # this job will be trigger only if the label get-perf is
    if: ${{ github.event.label.name == 'get-perf' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: SetUp and install everything
        run: |
            rm -rf .benchmarks
            pip install -r requirements.txt

      - name: Run perf on master based on pytest
        run: ./.github/workflows/perf.sh master

      - name: Run perf on current branch based on pytest
        run: ./.github/workflows/perf.sh ${{ github.event.pull_request.head.ref }}

      - name: Comment the report on PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ## Performances Reports
            $(./.github/workflows/perf_comment.sh ${{ github.event.pull_request.head.ref }})
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
